// GENERATED by scripts/gen-app-mounts.mjs — do not edit.
// The body lives in entities/client-programs/routes/admin/(dashboard)/edges/client-roadmaps/page; this file
// exists because Next binds a route by the exports of the file under app/.
// Anything below that a re-export cannot carry is declared by the entity, in
// its mounts.ts.
export { default, metadata } from "@/entities/client-programs/routes/admin/(dashboard)/edges/client-roadmaps/page";

export const dynamic = "force-dynamic";
