// Summarize a call transcript attached to a performance review, structured
// against the eleven review dimensions. Same fail-soft shape as
// entities/assistant/lib/meeting-summary.ts and lib/coaching/ai.ts: never throws to the caller,
// records its own state on the row. Because performance_reviews has no dedicated
// ai_status/ai_error columns, all AI state lives inside
// metadata.transcript_summary (read-modify-write of the metadata jsonb).
//
// The result is a DRAFT: it is shown as a review card for the manager to read
// and edit, and only folded into the overall review on explicit approval (PR 2).
//
// AUTHORIZATION IS THE CALLER'S JOB (the reviewer-gated server action). This runs
// on the service-role companyOs client and never enforces visibility itself.

import { anthropicIfConfigured } from "@/kernel/ai/client";
import { modelFor } from "@/kernel/ai/models";
import { companyOs } from "@/kernel/data/supabase";
import { REVIEW_DIMENSIONS } from "@/entities/team/lib/reviews";
import { readReviewTranscript } from "@/entities/team/lib/reviews/transcript";
import { readTextOutput } from "@/kernel/ai/response";

const MODEL = modelFor("review-summary", "standard");
const MAX_TRANSCRIPT_CHARS = 150_000;

type Ok = { ok: true };
type Err = { ok: false; error: string };

const clip = (s: string, max: number): string =>
  s.length > max ? `${s.slice(0, max)}\n\n[...truncated]` : s;

export type ReviewTranscriptSummary = {
  meeting_id: string | null;
  ai_status: "pending" | "ready" | "error";
  ai_model: string | null;
  ai_error: string | null;
  generated_at: string | null;
  overview: string | null;
  strengths: string[];
  growth_areas: string[];
  dimensions: { key: string; label: string; signal: string }[];
  // The labeled "From call" section, generated by the AI (the default text).
  section_markdown: string | null;
  // Whether the reviewer has folded this into the overall review, and the exact
  // (possibly edited) text that gets shown as the "From call" section.
  included: boolean;
  final_markdown: string | null;
};

// A function, not a module-level constant: it reads REVIEW_DIMENSIONS, and this
// module can be evaluated before reviews.ts finishes initialising (see labelByKey).
function SUMMARY_SCHEMA() {
  return {
  type: "object",
  additionalProperties: false,
  required: ["overview", "strengths", "growth_areas", "dimensions"],
  properties: {
    overview: {
      type: "string",
      description: "2-3 sentences: what this call was about and the overall read on the person's performance.",
    },
    strengths: {
      type: "array",
      items: { type: "string" },
      description: "Concrete strengths the call evidenced, one per item, each grounded in something actually said or shown. Empty array if none surfaced.",
    },
    growth_areas: {
      type: "array",
      items: { type: "string" },
      description: "Concrete areas for growth the call evidenced, one per item, grounded in the transcript. Empty array if none surfaced.",
    },
    dimensions: {
      type: "array",
      description: "Only the review dimensions this call actually touched. Skip dimensions the call gave no signal on. Empty array if the call touched none.",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["key", "signal"],
        properties: {
          key: {
            type: "string",
            enum: REVIEW_DIMENSIONS.map((d) => d.key),
            description: "The dimension key this signal maps to.",
          },
          signal: {
            type: "string",
            description: "One or two sentences on what the call showed about this dimension, with a concrete example where possible.",
          },
        },
      },
    },
  },
  } as const;
}

const SYSTEM = `You turn a call transcript into a structured input for a team member's performance review.

You are given the eleven review dimensions and a transcript. Extract only what the transcript actually evidences: strengths, growth areas, and per-dimension signals grounded in concrete moments. Never invent behavior the transcript does not show. If the call gave no signal on a dimension, leave it out. Be specific and fair, not flattering.

Ground rules:
- Never use em dashes anywhere in your output. Use commas, colons, periods, or parentheses instead.
- Attribute claims to the transcript. Prefer "she walked the team through the rollback plan" over vague praise.
- Handle any personal or sensitive context with care. This is a performance input, not a character verdict.`;

// Built on first use, not at module load. This module sits on an import cycle
// (reviews.ts -> the company-os door -> the team door -> here), and when the
// graph is entered from the performance-reviews cron, reviews.ts has not
// finished initialising when this file evaluates: reading REVIEW_DIMENSIONS
// here at load time threw "Cannot access before initialization" and 500ed
// the cron on every run.
let labelByKeyCache: Map<string, string> | null = null;
function labelByKey(): Map<string, string> {
  labelByKeyCache ??= new Map(REVIEW_DIMENSIONS.map((d) => [d.key, d.label]));
  return labelByKeyCache;
}

// Build the labeled "From call" markdown section (used in PR 2 to fold into the
// overall review; shown as-is in the draft card meanwhile).
function buildSection(parsed: {
  overview: string;
  strengths: string[];
  growth_areas: string[];
  dimensions: { key: string; signal: string }[];
}): string {
  const lines: string[] = [parsed.overview.trim()];
  if (parsed.strengths.length) {
    lines.push("", "Strengths:", ...parsed.strengths.map((s) => `- ${s}`));
  }
  if (parsed.growth_areas.length) {
    lines.push("", "Growth areas:", ...parsed.growth_areas.map((s) => `- ${s}`));
  }
  if (parsed.dimensions.length) {
    lines.push(
      "",
      "By dimension:",
      ...parsed.dimensions.map((d) => `- ${labelByKey().get(d.key) ?? d.key}: ${d.signal}`),
    );
  }
  return lines.join("\n");
}

// Merge a transcript_summary patch into the review's metadata without clobbering
// other keys, reading the current metadata first.
async function patchSummary(
  reviewId: string,
  patch: Partial<ReviewTranscriptSummary>,
): Promise<void> {
  const { data } = await companyOs
    .from("performance_reviews")
    .select("metadata")
    .eq("id", reviewId)
    .maybeSingle();
  const metadata = ((data?.metadata as Record<string, unknown> | null) ?? {}) as Record<string, unknown>;
  const current = (metadata.transcript_summary as Partial<ReviewTranscriptSummary> | undefined) ?? {};
  metadata.transcript_summary = { ...current, ...patch };
  await companyOs
    .from("performance_reviews")
    .update({ metadata })
    .eq("id", reviewId);
}

// Reset the summary to a clean pending state (called right after a transcript is
// saved, before the fire-and-forget summarize runs, so the UI shows "generating"
// and any prior summary/error is cleared).
export async function markReviewSummaryPending(reviewId: string, meetingId: string): Promise<void> {
  await patchSummary(reviewId, {
    meeting_id: meetingId,
    ai_status: "pending",
    ai_error: null,
    generated_at: null,
    overview: null,
    strengths: [],
    growth_areas: [],
    dimensions: [],
    section_markdown: null,
    // Replacing the transcript retracts any previously folded-in section: the
    // reviewer re-approves the fresh summary.
    included: false,
    final_markdown: null,
  });
}

// Fold the call summary into the overall review (or retract it). `finalMarkdown`
// is the reviewer's (possibly edited) section text; ignored when retracting.
// Authorization is the caller's job (the reviewer-gated server action).
export async function setReviewSummaryIncluded(
  reviewId: string,
  included: boolean,
  finalMarkdown: string | null,
): Promise<void> {
  await patchSummary(reviewId, {
    included,
    final_markdown: included ? (finalMarkdown?.trim() || null) : null,
  });
}

export async function summarizeReviewCall(reviewId: string): Promise<Ok | Err> {
  const fail = async (error: string): Promise<Err> => {
    await patchSummary(reviewId, { ai_status: "error", ai_error: error.slice(0, 500) });
    return { ok: false, error };
  };
  try {
    const anthropic = anthropicIfConfigured();
    if (!anthropic) return fail("ANTHROPIC_API_KEY is not configured.");

    const transcript = await readReviewTranscript(reviewId);
    if (!transcript?.trim()) return fail("No transcript on this review yet.");

    const dimensionList = REVIEW_DIMENSIONS.map((d) => `- ${d.key}: ${d.label}`).join("\n");
    const response = await anthropic.messages.create({
      model: MODEL,
      max_tokens: 4000,
      system: SYSTEM,
      output_config: { effort: "medium", format: { type: "json_schema", schema: SUMMARY_SCHEMA() } },
      messages: [
        {
          role: "user",
          content: `# Review dimensions\n${dimensionList}\n\n# Call transcript\n${clip(
            transcript,
            MAX_TRANSCRIPT_CHARS,
          )}\n\nExtract the structured review input.`,
        },
      ],
    });
    const out = readTextOutput("review-summary", MODEL, response, "The model declined this transcript.");
    if (!out.ok) return fail(out.error);
    const parsed = JSON.parse(out.text) as {
      overview: string;
      strengths: string[];
      growth_areas: string[];
      dimensions: { key: string; signal: string }[];
    };
    if (!parsed.overview?.trim()) return fail("Model output was missing an overview.");

    const dimensions = (parsed.dimensions ?? [])
      .filter((d) => labelByKey().has(d.key) && d.signal?.trim())
      .map((d) => ({ key: d.key, label: labelByKey().get(d.key)!, signal: d.signal.trim() }));

    await patchSummary(reviewId, {
      ai_status: "ready",
      ai_model: MODEL,
      ai_error: null,
      generated_at: new Date().toISOString(),
      overview: parsed.overview.trim(),
      strengths: (parsed.strengths ?? []).filter((s) => s?.trim()),
      growth_areas: (parsed.growth_areas ?? []).filter((s) => s?.trim()),
      dimensions,
      section_markdown: buildSection({
        overview: parsed.overview,
        strengths: (parsed.strengths ?? []).filter((s) => s?.trim()),
        growth_areas: (parsed.growth_areas ?? []).filter((s) => s?.trim()),
        dimensions,
      }),
    });
    return { ok: true };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`[review-ai] summary ${reviewId} failed:`, msg);
    return fail(msg);
  }
}
