// GENERATED by scripts/gen-app-mounts.mjs — do not edit.
// The body lives in entities/portal/routes/portal/(auth)/layout; this file
// exists because Next binds a route by the exports of the file under app/.
// Anything below that a re-export cannot carry is declared by the entity, in
// its mounts.ts.
import "../../admin/admin.css";
import "@/app/styles/utilities.css";
export { default, metadata } from "@/entities/portal/routes/portal/(auth)/layout";
