// GENERATED by scripts/gen-deployment.mjs from deployments/edge8.json — do not edit.
//
// Every surface's navigation, composed from the entities this deployment
// installs. `app/` is the only place that knows which those are, which is why
// the composition happens here and not in the kernel (which may name no entity)
// or in an entity (which would have to name its peers). Each shell owns its
// information architecture and its slots; each entity owns its rows, and a row
// that depends on who is looking carries a `when` capability the shell
// resolves per request.
//
// Regenerate with `npm run gen:deployment`; `npm run check:generated` fails
// when this file and the deployment disagree.
import { composeNav, type NavContribution, type NavSection } from "@/kernel/shell/nav";
import { ADMIN_SLOTS } from "@/kernel/shell/admin-ia";
import { TEAM_SLOTS } from "@/kernel/shell/team-ia";
import { PORTAL_SLOTS } from "@/kernel/shell/portal-ia";

import { adminNav as boardsAdminNav } from "@/entities/boards/client";
import { adminNav as campaignsAdminNav } from "@/entities/campaigns/client";
import { adminNav as clientProgramsAdminNav } from "@/entities/client-programs/client";
import { adminNav as companyOsAdminNav } from "@/entities/company-os/client";
import { adminNav as crmAdminNav } from "@/entities/crm/client";
import { adminNav as hiringAdminNav } from "@/entities/hiring/client";
import { adminNav as ideasAdminNav } from "@/entities/ideas/client";
import { adminNav as onboardingAdminNav } from "@/entities/onboarding/client";
import { adminNav as orgAdminNav } from "@/entities/org/client";
import { adminNav as retreatsAdminNav } from "@/entities/retreats/client";
import { adminNav as teamAdminNav } from "@/entities/team/client";
import { adminNav as timeOffAdminNav } from "@/entities/time-off/client";

const ADMIN_NAV_CONTRIBUTIONS: NavContribution[] = [
  ...boardsAdminNav,
  ...campaignsAdminNav,
  ...clientProgramsAdminNav,
  ...companyOsAdminNav,
  ...crmAdminNav,
  ...hiringAdminNav,
  ...ideasAdminNav,
  ...onboardingAdminNav,
  ...orgAdminNav,
  ...retreatsAdminNav,
  ...teamAdminNav,
  ...timeOffAdminNav,
];

export const ADMIN_NAV: NavSection[] = composeNav(ADMIN_SLOTS, ADMIN_NAV_CONTRIBUTIONS);

import { teamNav as boardsTeamNav } from "@/entities/boards/client";
import { teamNav as coachingTeamNav } from "@/entities/coaching/client";
import { teamNav as crmTeamNav } from "@/entities/crm/client";
import { teamNav as hiringTeamNav } from "@/entities/hiring/client";
import { teamNav as ideasTeamNav } from "@/entities/ideas/client";
import { teamNav as onboardingTeamNav } from "@/entities/onboarding/client";
import { teamNav as orgTeamNav } from "@/entities/org/client";
import { teamNav as teamTeamNav } from "@/entities/team/client";
import { teamNav as timeOffTeamNav } from "@/entities/time-off/client";

const TEAM_NAV_CONTRIBUTIONS: NavContribution[] = [
  ...boardsTeamNav,
  ...coachingTeamNav,
  ...crmTeamNav,
  ...hiringTeamNav,
  ...ideasTeamNav,
  ...onboardingTeamNav,
  ...orgTeamNav,
  ...teamTeamNav,
  ...timeOffTeamNav,
];

export const TEAM_NAV: NavSection[] = composeNav(TEAM_SLOTS, TEAM_NAV_CONTRIBUTIONS);

import { portalNav as portalPortalNav } from "@/entities/portal/client";
import { portalNav as timeOffPortalNav } from "@/entities/time-off/client";

const PORTAL_NAV_CONTRIBUTIONS: NavContribution[] = [
  ...portalPortalNav,
  ...timeOffPortalNav,
];

export const PORTAL_NAV: NavSection[] = composeNav(PORTAL_SLOTS, PORTAL_NAV_CONTRIBUTIONS);
