// GENERATED by scripts/gen-deployment.mjs from deployments/edge8.json — do not edit.
//
// What the hand-written shells under app/ take from entities. A shell may not
// import an entity directly: it does not know which entities this deployment
// installs, and an import of one that is not installed still bundles it. Each
// slot below is provided by one entity when that entity is installed and by a
// fallback otherwise, so the same layout files serve every deployment.
//
// Regenerate with `npm run gen:deployment`; `npm run check:generated` fails
// when this file and the deployment disagree.
import { createElement, Fragment, type ReactNode } from "react";
import { AdminAssistant as AdminAssistantProvided } from "@/entities/assistant";
import { avatarUrlForAuthUser as avatarUrlForAuthUserProvided } from "@/entities/retreats";
import { SiteFrame as SiteFrameProvided, SITE_TITLE as SITE_TITLEProvided, SITE_DESCRIPTION as SITE_DESCRIPTIONProvided, SITE_NAME as SITE_NAMEProvided, LOGO_SRC as LOGO_SRCProvided } from "@/entities/site";

// the admin shell's chat pane; nothing when the assistant is not installed.
export const AdminAssistant: ((props: { email: string | null | undefined }) => JSX.Element) | null = AdminAssistantProvided;

// the signed-in admin's avatar; no avatar when retreats (which owns the media) is not installed.
export const avatarUrlForAuthUser: (userId: string) => Promise<string | null> = avatarUrlForAuthUserProvided;

// the public site's header and footer around every page; a bare frame without the site.
export const SiteFrame: (props: { children: ReactNode }) => ReactNode = SiteFrameProvided;

// head copy from the site entity.
export const SITE_TITLE: string = SITE_TITLEProvided;

// head copy from the site entity.
export const SITE_DESCRIPTION: string = SITE_DESCRIPTIONProvided;

// head copy from the site entity.
export const SITE_NAME: string = SITE_NAMEProvided;

// schema.org logo from the site entity.
export const LOGO_SRC: string = LOGO_SRCProvided;
