// GENERATED by scripts/gen-app-mounts.mjs — do not edit.
// The body lives in entities/coaching/crons/coaching-recaps; this file
// exists because Next binds a route by the exports of the file under app/.
// Anything below that a re-export cannot carry is declared by the entity, in
// its mounts.ts.
export { GET } from "@/entities/coaching/crons/coaching-recaps";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 300;
