import fs from "node:fs";
import { pathToFileURL } from "node:url";
import path from "node:path";
import { episodeSlug } from "./lib.mjs";
import { buildTimeline } from "./timeline.mjs";

/**
 * Burned-in captions, written as ASS.
 *
 * Not SRT: SRT carries no styling, so the 86% scrim and the 160px lift off the
 * base would be lost, and those two things are what make a caption readable in
 * a muted LinkedIn autoplay on a phone. The ffmpeg subtitles filter reads ASS
 * styling directly.
 *
 * Style values come from the brand kit, section 04.
 */

// ASS colours are &HAABBGGRR. #101014 at 86% opaque scrim: alpha 0x24 is the
// 14% transparency the kit asks for.
const SCRIM = "&H24141010";
const WHITE = "&H00FFFFFF";

// ASS hard line break. Written this way so no build step or shell can eat the
// backslash on the way in.
const BREAK = String.fromCharCode(92) + "N";

const stamp = (seconds) => {
  const s = Math.max(0, seconds);
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const rest = s % 60;
  return `${h}:${String(m).padStart(2, "0")}:${rest.toFixed(2).padStart(5, "0")}`;
};

export function renderAss(timeline) {
  const head = [
    "[Script Info]",
    "; 8 Edges demo series caption style. Generated by video/scripts/captions.mjs.",
    "ScriptType: v4.00+",
    "PlayResX: 1920",
    "PlayResY: 1080",
    "WrapStyle: 2",
    "ScaledBorderAndShadow: yes",
    "YCbCr Matrix: TV.709",
    "",
    "[V4+ Styles]",
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
    // BorderStyle 3 is the opaque box. Outline 14 is the padding around the
    // text, which lands close to the 8px / 22px the kit specifies.
    `Style: E8,Manrope,52,${WHITE},${WHITE},${SCRIM},${SCRIM},0,0,0,0,100,100,0,0,3,14,0,2,96,96,160,1`,
    "",
    "[Events]",
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
  ];
  const events = timeline.cues.map(
    (cue) => `Dialogue: 0,${stamp(cue.start)},${stamp(cue.end)},E8,,0,0,0,,${cue.lines.join(BREAK)}`,
  );
  return [...head, ...events, ""].join("\n");
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const slug = episodeSlug();
  const timeline = buildTimeline(slug);
  const file = path.join(timeline.dir, "captions.ass");
  fs.writeFileSync(file, renderAss(timeline), "utf8");
  console.log(`${timeline.cues.length} cues → ${file}`);
}
