// GENERATED by scripts/gen-app-mounts.mjs — do not edit.
// The body lives in entities/time-off/routes/team/(dashboard)/time-off/page; this file
// exists because Next binds a route by the exports of the file under app/.
// Anything below that a re-export cannot carry is declared by the entity, in
// its mounts.ts.
export { default, metadata } from "@/entities/time-off/routes/team/(dashboard)/time-off/page";

export const dynamic = "force-dynamic";
