// GENERATED by scripts/gen-app-mounts.mjs — do not edit.
// The body lives in entities/company-os/api/admin/chat/route; this file
// exists because Next binds a route by the exports of the file under app/.
// Anything below that a re-export cannot carry is declared by the entity, in
// its mounts.ts.
export { POST } from "@/entities/company-os/api/admin/chat/route";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 300;
