// Generates the three derived artifacts from docs/db/data-dictionary.md (the
// single source of truth): the COMMENT ON migration, the lookup index inside
// .claude/skills/data-dictionary/SKILL.md, and the Dictionary tab + embedded
// comments inside private-docs/workflows/private/e8/data-atlas.html.
// Never hand-edit those artifacts.
//
//   node scripts/data-dictionary/generate.mjs                  # skill index + atlas tab, SQL to stdout
//   node scripts/data-dictionary/generate.mjs --sql-out FILE   # also write the migration file
//   node scripts/data-dictionary/generate.mjs --check          # exit 1 if skill index or atlas tab is stale
import { readFileSync, writeFileSync } from "node:fs";

const DICT = "docs/db/data-dictionary.md";
const SKILL = ".claude/skills/data-dictionary/SKILL.md";
const ATLAS = "private-docs/workflows/private/e8/data-atlas.html";
const START = "<!-- INDEX:START (generated - run scripts/data-dictionary/generate.mjs) -->";
const END = "<!-- INDEX:END -->";
const HSTART = "<!-- DICT:START (generated - run scripts/data-dictionary/generate.mjs) -->";
const HEND = "<!-- DICT:END -->";

// The atlas DATA snapshot may lag pending rename migrations. Map canonical
// (post-rename) names to the atlas card key so comments land until it refreshes.
const ATLAS_ALIASES = {
  "company_os.marketing_content": "marketing_calendar",
  "company_os.compensation_sensitive": "compensation",
  "company_os.company_information": "team_knowledge",
  "company_os.meeting_associations": "meeting_links",
  "company_os.goals": "coaching_goals",
};
// Atlas cards whose table is dropped or renamed in repo main but still drawn.
const ATLAS_STALE_NOTES = {
  meeting_notes: "DROPPED 28 Aug 2026 — folded into meetings as source='notes' rows.",
  goals: "DROPPED 28 Aug 2026 — legacy table; coaching_goals was promoted to the goals name.",
  campaigns: "DROPPED 28 Aug 2026 — superseded by marketing_campaigns.",
  meeting_links: "RENAMED 28 Aug 2026 — now meeting_associations.",
};

const md = readFileSync(DICT, "utf8").replace(/^```[\s\S]*?^```$/gm, "");
const entries = [];
for (const block of md.split(/^### /m).slice(1)) {
  const lines = block.split("\n");
  const table = lines[0].trim();
  if (!/^[a-z0-9_]+\.[a-z0-9_]+$/.test(table)) continue;
  const field = (name) => {
    const line = lines.find((l) => l.startsWith(name + ":"));
    return line ? line.slice(name.length + 1).trim() : "";
  };
  const cols = [];
  const ci = lines.findIndex((l) => l.trim() === "Columns:");
  if (ci >= 0) {
    for (let i = ci + 1; i < lines.length; i++) {
      const m = lines[i].match(/^- ([a-z0-9_]+): (.+)$/);
      if (!m) break;
      cols.push({ name: m[1], desc: m[2].trim() });
    }
  }
  entries.push({
    table,
    grain: field("One row is"),
    bucket: field("Bucket"),
    tier: field("Tier"),
    status: field("Status"),
    origin: field("Origin"),
    usage: field("Usage"),
    reuse: field("Reuse"),
    donot: field("Do not"),
    cols,
  });
}
if (entries.length === 0) {
  console.error("No entries parsed from " + DICT + " - check the entry format.");
  process.exit(1);
}

// Mined code-usage evidence (node scripts/data-dictionary/mine-usage.mjs).
let USAGE_RAW = {};
try { USAGE_RAW = JSON.parse(readFileSync("scripts/data-dictionary/column-usage.json", "utf8")); } catch {}
// Compact for embedding: one file-path array, index lists per table/column.
const fileIdx = new Map();
const fid = (f) => { if (!fileIdx.has(f)) fileIdx.set(f, fileIdx.size); return fileIdx.get(f); };
const USAGE = { files: [], tables: {} };
for (const [t, u] of Object.entries(USAGE_RAW)) {
  USAGE.tables[t] = { f: u.files.slice(0, 12).map(fid), c: {} };
  for (const [c, fs] of Object.entries(u.cols)) USAGE.tables[t].c[c] = fs.slice(0, 6).map(fid);
}
USAGE.files = [...fileIdx.keys()];

const q = (s) => s.replace(/'/g, "''");
const tableComment = (e) => {
  const warn = e.status === "superseded" ? "SUPERSEDED - do not write here; see the data dictionary for the replacement. " : "";
  return warn + "One row is: " + e.grain + ` [${e.bucket} | tier ${e.tier} | ${e.status}]`;
};
const sqlLines = [
  "-- GENERATED by scripts/data-dictionary/generate.mjs from docs/db/data-dictionary.md.",
  "-- Do not hand-edit: edit the dictionary and regenerate.",
  "",
];
for (const e of entries) {
  if (e.status === "dead") continue;
  sqlLines.push(`comment on table ${e.table} is '${q(tableComment(e))}';`);
  for (const c of e.cols) sqlLines.push(`comment on column ${e.table}.${c.name} is '${q(c.desc)}';`);
  sqlLines.push("");
}
const sql = sqlLines.join("\n");

// ---- skill index ----
const index = entries
  .map((e) => `- ${e.table} — ${e.grain} (${e.bucket}; tier ${e.tier}; ${e.status})`)
  .join("\n");
const skill = readFileSync(SKILL, "utf8");
const si = skill.indexOf(START), ei = skill.indexOf(END);
if (si < 0 || ei < 0) { console.error("Index markers not found in " + SKILL); process.exit(1); }
const skillNext = skill.slice(0, si + START.length) + "\n" + index + "\n" + skill.slice(ei);

// ---- atlas: embedded comments + Dictionary tab ----
const atlas = readFileSync(ATLAS, "utf8");
const dm = atlas.match(/const DATA = (\{[\s\S]*?\});\n/);
if (!dm) { console.error("const DATA not found in " + ATLAS); process.exit(1); }
const data = JSON.parse(dm[1]);
const atlasKey = (t) =>
  ATLAS_ALIASES[t] ?? (t.startsWith("htt.") ? t : t.replace(/^company_os\./, ""));
for (const e of entries) {
  const k = atlasKey(e.table);
  const info = data.tables[k];
  if (!info || e.status === "dead") continue;
  info.c = tableComment(e) + (k !== (e.table.startsWith("htt.") ? e.table : e.table.split(".")[1]) ? ` (renamed: now ${e.table})` : "");
  for (const c of e.cols) {
    const col = info.cols.find((a) => a[0] === c.name);
    if (col) col[4] = c.desc;
  }
}
for (const [k, note] of Object.entries(ATLAS_STALE_NOTES)) {
  if (data.tables[k]) data.tables[k].c = note;
}
const usageKey = (t) => (t.startsWith("htt.") ? t : t.replace(/^company_os\./, ""));
const dictJson = entries.map((e) => ({
  t: e.table, k: data.tables[atlasKey(e.table)] ? atlasKey(e.table) : null, uk: usageKey(e.table),
  g: e.grain, b: e.bucket, ti: e.tier, s: e.status,
  o: e.origin, u: e.usage, re: e.reuse, dn: e.donot,
}));
const tab = `${HSTART}
<style>
  #dict-toggle.on { border-color: var(--mint); color: var(--mint); }
  #dictpanel { position: fixed; top: 52px; left: 272px; right: 0; bottom: 0; z-index: 32; background: var(--dark); display: none; flex-direction: column; }
  body.dict-open #dictpanel { display: flex; }
  body.dict-open #minimap, body.dict-open #hint { display: none; }
  @media (max-width: 860px) { #dictpanel { left: 0; } }
  #dicthead { padding: 12px 18px; border-bottom: 1px solid var(--border); display: flex; gap: 12px; align-items: center; flex-wrap: wrap; }
  #dictsearch { width: min(420px, 100%); height: 34px; background: var(--card); border: 1px solid var(--border); border-radius: 8px; color: var(--text); padding: 0 10px; font-size: 13px; outline: none; }
  #dictsearch:focus { border-color: var(--blue); }
  #dictcount { font-size: 12px; color: var(--muted); }
  #dictbody { flex: 1; overflow-y: auto; padding: 8px 18px 60px; }
  .dict-tierhead { padding: 18px 0 6px; font-size: 12px; font-weight: 800; text-transform: uppercase; letter-spacing: 0.05em; color: var(--mint); }
  details.dict-row { border-bottom: 1px solid rgba(234,238,242,0.06); }
  details.dict-row > summary { list-style: none; cursor: pointer; display: flex; gap: 10px; align-items: baseline; padding: 8px 4px; }
  details.dict-row > summary::-webkit-details-marker { display: none; }
  .dict-name { font-family: var(--mono); font-size: 13px; font-weight: 700; white-space: nowrap; }
  .dict-grain { font-size: 12.5px; color: var(--muted); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; flex: 1; }
  .dict-chip { flex: none; font-size: 9px; font-weight: 700; padding: 2px 7px; border-radius: 999px; text-transform: uppercase; letter-spacing: 0.04em; }
  .st-active { background: rgba(111,242,193,0.14); color: var(--mint); }
  .st-waiting { background: rgba(59,140,245,0.16); color: var(--blue); }
  .st-hold { background: rgba(234,179,8,0.16); color: #eab308; }
  .st-superseded, .st-dead { background: rgba(239,68,68,0.15); color: #f87171; }
  .dict-detail { padding: 2px 4px 12px 4px; font-size: 12.5px; color: var(--muted); line-height: 1.55; }
  .dict-detail b { color: var(--text); font-weight: 600; }
  .dict-detail div { margin-top: 4px; }
  .dict-jump { color: var(--blue); cursor: pointer; font-size: 11px; }
  .dict-jump:hover { text-decoration: underline; }
  .dict-cols { margin-top: 8px; border-top: 1px solid rgba(234,238,242,0.08); }
  .dict-colrow { display: flex; flex-wrap: wrap; gap: 8px; align-items: baseline; padding: 3px 0; border-bottom: 1px solid rgba(234,238,242,0.04); font-size: 11.5px; }
  .dict-colrow .cn { font-family: var(--mono); font-weight: 600; color: var(--text); }
  .dict-colrow .cn.pk { color: var(--mint); }
  .dict-colrow .cn.fk { color: var(--blue); }
  .dict-colrow .ct { font-family: var(--mono); color: var(--dim); font-size: 10.5px; }
  .dict-colrow .cd { color: var(--muted); flex: 1; min-width: 180px; }
  .dict-colrow .cu { color: var(--dim); font-size: 10.5px; margin-left: 8px; }
</style>
<div id="dictpanel">
  <div id="dicthead">
    <input id="dictsearch" type="search" placeholder="Search the dictionary… (tables, columns, usage, reuse rules)" autocomplete="off">
    <div id="dictcount"></div>
  </div>
  <div id="dictbody"></div>
</div>
<script>
const DICT = ${JSON.stringify(dictJson)};
const USAGE = ${JSON.stringify(USAGE)};
(function(){
  const btn = document.createElement('button');
  btn.className = 'btn'; btn.id = 'dict-toggle'; btn.textContent = 'Dictionary';
  document.querySelector('#topbar .ctl').prepend(btn);
  const panel = document.getElementById('dictpanel');
  const body = document.getElementById('dictbody');
  const count = document.getElementById('dictcount');
  const input = document.getElementById('dictsearch');
  btn.onclick = () => { document.body.classList.toggle('dict-open'); btn.classList.toggle('on'); if (document.body.classList.contains('dict-open')) render(input.value); };
  const esc2 = (s) => String(s||'').replace(/[&<>"]/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const CONV = { id: 'Primary key.', created_at: 'Row creation time.', updated_at: 'Last modification time.',
    archived_at: 'Soft-delete timestamp; null means live (house rule 5).', archived_by: 'Who archived the row.',
    metadata: 'JSONB escape hatch for experimental attributes.', currency: 'ISO currency of the money columns on this row.',
    amount_cents: 'Money in minor units (house rule 4 - never floats).', amount_usd_cents: 'USD-normalized amount in cents.',
    fx_rate: 'FX rate used for the USD normalization.', synced_at: 'Last sync from the external system of record.',
    external_id: 'Id of this record in the external system of record.', notes: 'Free-text notes.' };
  const colsOf = (e) => (e.k && DATA.tables[e.k] ? DATA.tables[e.k].cols : []);
  const short = (f) => f.split('/').slice(-2).join('/');
  const usedIn = (e, col) => {
    const u = USAGE.tables[e.uk]; if (!u) return null;
    const idxs = col ? u.c[col] : u.f;
    if (!idxs || !idxs.length) return null;
    return idxs.map(i => USAGE.files[i]);
  };
  const colDesc = (c) => c[4] ? c[4] : (c[3] ? 'References ' + c[3] + '.' : (CONV[c[0]] || ''));
  function render(qs) {
    qs = (qs||'').toLowerCase();
    const hit = DICT.filter(e => !qs || (e.t + ' ' + e.g + ' ' + e.b + ' ' + e.o + ' ' + e.u + ' ' + e.re + ' ' + e.dn + ' ' + colsOf(e).map(c => c[0] + ' ' + (c[4]||'')).join(' ')).toLowerCase().includes(qs));
    count.textContent = hit.length + ' of ' + DICT.length + ' tables';
    const tiers = [['1 spine','Tier 1 · the spine'],['2 stage engine','Tier 2 · stage engines'],['3 support','Tier 3 · support']];
    let h = '';
    for (const [key, label] of tiers) {
      const grp = hit.filter(e => e.ti === key);
      if (!grp.length) continue;
      h += '<div class="dict-tierhead">' + label + ' (' + grp.length + ')</div>';
      for (const e of grp) {
        h += '<details class="dict-row"><summary><span class="dict-name">' + esc2(e.t) + '</span>'
          + '<span class="dict-chip st-' + esc2(e.s.split(' ')[0]) + '">' + esc2(e.s) + '</span>'
          + '<span class="dict-grain">' + esc2(e.g) + '</span></summary><div class="dict-detail">'
          + '<div><b>' + esc2(e.b) + '</b></div>'
          + (e.o ? '<div><b>Origin.</b> ' + esc2(e.o) + '</div>' : '')
          + (e.u ? '<div><b>Usage.</b> ' + esc2(e.u) + '</div>' : '')
          + (e.re ? '<div><b>Reuse.</b> ' + esc2(e.re) + '</div>' : '')
          + (e.dn ? '<div><b>Do not.</b> ' + esc2(e.dn) + '</div>' : '')
          + usageHtml(e)
          + colHtml(e)
          + (e.k ? '<div class="dict-jump" data-k="' + esc2(e.k) + '">Show on the map →</div>' : '')
          + '</div></details>';
      }
    }
    body.innerHTML = h || '<div class="no-results">Nothing matches.</div>';
    body.querySelectorAll('.dict-jump').forEach(el => el.onclick = () => {
      document.body.classList.remove('dict-open'); btn.classList.remove('on');
      if (typeof select === 'function') select(el.dataset.k);
    });
  }
  function usageHtml(e) {
    const uf = usedIn(e, null);
    if (!uf) return '<div><b>Where used.</b> No direct references found in app code.</div>';
    return '<div><b>Where used.</b> ' + esc2(uf.slice(0, 6).map(short).join(', ')) + (uf.length > 6 ? ' +' + (uf.length - 6) + ' more' : '') + ' <span title="' + esc2(uf.join(String.fromCharCode(10))) + '">(hover for full paths)</span></div>';
  }
  function colHtml(e) {
    const cols = colsOf(e);
    if (!cols.length) return '';
    let h = '<div class="dict-cols"><div style="padding:6px 0 2px;"><b>Columns (' + cols.length + ').</b></div>';
    for (const c of cols) {
      const cls = (c[2] & 1) ? 'cn pk' : ((c[2] & 2) ? 'cn fk' : 'cn');
      const uf = usedIn(e, c[0]);
      const uHtml = uf ? '<span class="cu" title="' + esc2(uf.join(String.fromCharCode(10))) + '">used in ' + esc2(uf.slice(0,2).map(short).join(', ')) + (uf.length > 2 ? ' +' + (uf.length - 2) : '') + '</span>' : '';
      h += '<div class="dict-colrow"><span class="' + cls + '">' + esc2(c[0]) + '</span>'
        + '<span class="ct">' + esc2(c[1]) + ((c[2] & 4) ? '' : ' · nullable') + '</span>'
        + '<span class="cd">' + esc2(colDesc(c)) + uHtml + '</span></div>';
    }
    return h + '</div>';
  }
  input.addEventListener('input', () => render(input.value));
})();
</script>
${HEND}`;

let atlasNext = atlas.replace(dm[0], "const DATA = " + JSON.stringify(data) + ";\n");
const hs = atlasNext.indexOf(HSTART), he = atlasNext.indexOf(HEND);
if (hs >= 0 && he >= 0) {
  atlasNext = atlasNext.slice(0, hs) + tab + atlasNext.slice(he + HEND.length);
} else {
  atlasNext = atlasNext.replace("</body>", tab + "\n</body>");
}

if (process.argv.includes("--check")) {
  let stale = [];
  if (skillNext !== skill) stale.push(SKILL);
  if (atlasNext !== atlas) stale.push(ATLAS);
  if (stale.length) {
    console.error("Stale generated artifacts: " + stale.join(", ") + ". Run: node scripts/data-dictionary/generate.mjs");
    process.exit(1);
  }
  console.log(`Generated artifacts are fresh (${entries.length} entries).`);
  process.exit(0);
}

writeFileSync(SKILL, skillNext);
writeFileSync(ATLAS, atlasNext);
const out = process.argv.indexOf("--sql-out");
if (out >= 0 && process.argv[out + 1]) {
  writeFileSync(process.argv[out + 1], sql);
  console.log(`Wrote ${process.argv[out + 1]}, refreshed ${SKILL} and ${ATLAS} (${entries.length} entries).`);
} else {
  console.log(sql);
  console.error(`Refreshed ${SKILL} and ${ATLAS} (${entries.length} entries).`);
}
