// GENERATED by scripts/gen-app-mounts.mjs — do not edit.
// The body lives in entities/hiring/routes/admin/(dashboard)/talent/applications/[id]/page; this file
// exists because Next binds a route by the exports of the file under app/.
// Anything below that a re-export cannot carry is declared by the entity, in
// its mounts.ts.
export { default, generateMetadata } from "@/entities/hiring/routes/admin/(dashboard)/talent/applications/[id]/page";

export const dynamic = "force-dynamic";
export const fetchCache = "force-no-store";
