// Country vocabulary for admin dropdowns. Display names (not ISO codes) so the
// select value matches what is already stored on companies/people (free text
// like "Australia"). When an existing record holds a value that isn't in this
// list, the form preserves it as an extra option rather than blanking it.
export const COUNTRIES = [
  "Australia",
  "New Zealand",
  "United States",
  "United Kingdom",
  "Canada",
  "Ireland",
  "Vietnam",
  "Singapore",
  "Malaysia",
  "Indonesia",
  "Philippines",
  "Thailand",
  "India",
  "Japan",
  "South Korea",
  "China",
  "Hong Kong",
  "Taiwan",
  "United Arab Emirates",
  "Saudi Arabia",
  "Qatar",
  "Israel",
  "South Africa",
  "Nigeria",
  "Kenya",
  "Egypt",
  "Germany",
  "France",
  "Netherlands",
  "Belgium",
  "Spain",
  "Portugal",
  "Italy",
  "Switzerland",
  "Austria",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Poland",
  "Czech Republic",
  "Romania",
  "Greece",
  "Turkey",
  "Ukraine",
  "Mexico",
  "Brazil",
  "Argentina",
  "Chile",
  "Colombia",
  "Peru",
] as const;
